{% set name = "napari-allencell-segmenter" %}
{% set version = "2.1.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-allencell-segmenter-{{ version }}.tar.gz
  sha256: acd1e7bcc5ed6437dbc9dbca29a37071d87d69033408bf61c175f6c529335aaf

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - pytest-runner
    - python >=3.7
    - setuptools-scm
  run:
    - aicsimageio >=4.0.5
    - aicssegmentation >=0.5.3
    - importlib-metadata ==4.11.4
    - magicgui >=0.2.9
    - napari >=0.4.9
    - napari-plugin-engine >=0.1.4
    - npe2
    - numpy
    - ome-zarr
    - opencv >=4.5.1
    - python >=3.7
    - qtpy

test:
  imports:
    - napari_allencell_segmenter
  commands:
    - pip list
    # - pip check
  requires:
    - pip

about:
  home: https://github.com/AllenCell/napari-allencell-segmenter
  summary: A plugin that enables 3D image segmentation provided by Allen Institute for Cell Science
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - yrkim98
